# TincyCo project

In [2]:
import pandas as pd

## sheet SKU Master

In [3]:
Tincy_SKU_Master=pd.read_excel('TincyCo.xlsx',sheet_name='SKU Master')
Tincy_SKU_Master

Department  Class  Style  Color          SKU  Cost  Price  \
0       800.0    5.0   20.0    2.0   8000520021   7.5   9.99   
1       800.0    4.0   51.0   11.0   8000451112   9.0  12.99   
2       731.0   24.0   55.0   52.0   7312455520  25.0  31.99   
3       731.0   24.0   55.0   53.0   7312455530  14.5  22.99   
4      5001.0  201.0   12.0    4.0  50012011240   2.5   7.99   
5      5001.0  201.0   12.0    5.0  50012011250   7.5   9.99   
6         NaN    NaN    NaN    NaN  50012011340   6.0   5.99   
7      5001.0  201.0   13.0    4.0  50012011341   8.0   6.99   
8      5001.0  300.0    1.0    1.0  50013000110   6.5  12.99   

                  Vendor  
0  MA Excellent Products  
1  MA Excellent Products  
2  MA Excellent Products  
3  GA General Wholesales  
4          China Imports  
5          China Imports  
6          China Imports  
7          China Imports  
8          China Imports

In [4]:
Tincy_SKU_Master.isna().sum()

Department    1
Class         1
Style         1
Color         1
SKU           0
Cost          0
Price         0
Vendor        0
dtype: int64

In [5]:
Tincy_SKU_Master.drop_duplicates(inplace=True)

In [6]:
MA_Excellent_Products_SKU=['8000520021','8000451112','7312455520']

## 1-sheet store 312

In [7]:
Tincy_Store_312=pd.read_excel('TincyCo.xlsx',sheet_name='Store 312')
Tincy_Store_312

DB_ID          SKU  Store       Date Unit Sales  Dollar Sales
0       79444  50012011250    312 2014-08-04          3         29.97
1       79445  50012011250    312 2014-08-05          2         19.98
2       79446  50012011250    312 2014-08-06          5         49.95
3       79447  50012011250    312 2014-08-07          3         29.97
4       79448  50012011250    312 2014-08-08          7         69.93
...       ...          ...    ...        ...        ...           ...
3691  2001791  50012011240    312 2016-08-02          1          7.99
3692  2001792  50012011240    312 2016-08-03        NaN           NaN
3693  2001793  50012011240    312 2016-08-04          3         23.97
3694  2001794  50012011240    312 2016-08-05          1          7.99
3695  2001795  50012011240    312 2016-08-06          3         23.97

[3696 rows x 6 columns]

In [8]:
Tincy_Store_312.isna().sum()

DB_ID            0
SKU              0
Store            0
Date             0
Unit Sales      50
Dollar Sales    80
dtype: int64

In [9]:
Tincy_Store_312.drop_duplicates(inplace=True)

In [10]:
Tincy_Store_312.dropna(inplace=True)

In [11]:
Tincy_Store_312.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3613 entries, 0 to 3695
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype         
---  ------        --------------  -----         
 0   DB_ID         3613 non-null   int64         
 1   SKU           3613 non-null   object        
 2   Store         3613 non-null   int64         
 3   Date          3613 non-null   datetime64[ns]
 4   Unit Sales    3613 non-null   object        
 5   Dollar Sales  3613 non-null   float64       
dtypes: datetime64[ns](1), float64(1), int64(2), object(2)
memory usage: 197.6+ KB


In [12]:
Tincy_Store_312['week']=Tincy_Store_312['Date'].dt.isocalendar().week
Tincy_Store_312

DB_ID          SKU  Store       Date Unit Sales  Dollar Sales  week
0       79444  50012011250    312 2014-08-04          3         29.97    32
1       79445  50012011250    312 2014-08-05          2         19.98    32
2       79446  50012011250    312 2014-08-06          5         49.95    32
3       79447  50012011250    312 2014-08-07          3         29.97    32
4       79448  50012011250    312 2014-08-08          7         69.93    32
...       ...          ...    ...        ...        ...           ...   ...
3690  2001790  50012011240    312 2016-08-01          2         15.98    31
3691  2001791  50012011240    312 2016-08-02          1          7.99    31
3693  2001793  50012011240    312 2016-08-04          3         23.97    31
3694  2001794  50012011240    312 2016-08-05          1          7.99    31
3695  2001795  50012011240    312 2016-08-06          3         23.97    31

[3613 rows x 7 columns]

find which week have top sale in store 312

In [13]:
Ma_Excellent_Products=Tincy_SKU_Master[Tincy_SKU_Master['Vendor']=='MA Excellent Products']['SKU']
Combine312=Tincy_Store_312[Tincy_Store_312['SKU'].isin(Ma_Excellent_Products)]

In [14]:
Weekly_Sales=Combine312.groupby('week')['Dollar Sales'].sum()
Top_Week=Weekly_Sales.idxmax()
Top_Sales=Weekly_Sales.max()
print(f"The week with the highst sales for MA Excellent products is in store 312 week {Top_Week} with sales of {Top_Sales}$.")

The week with the highst sales for MA Excellent products is in store 312 week 13 with sales of 6225.4$.


Calculate net profit for store 312

In [15]:
Tincy_Store_312['Year']=Tincy_Store_312['Date'].dt.year
merged312 = pd.merge(Tincy_SKU_Master, Tincy_Store_312, on='SKU')
china_import_df = merged312[merged312['Vendor'] == 'China Imports'].copy()
china_import_df['Net Profit'] = china_import_df['Dollar Sales'] - (china_import_df['Cost'] * china_import_df['Dollar Sales'] / china_import_df['Price'])
china_import_df.reset_index(drop=True)

china_import_df.groupby(["Year"])[['Net Profit']].sum().reset_index()

Year     Net Profit
0  2014  301674.235398
1  2015  229927.649174
2  2016  406862.992033

Best day for advertays item MA Excellent pruducts in store 312

In [16]:
Tincy_Store_312['Day']=Tincy_Store_312['Date'].dt.day_name()
merged_df = pd.merge(Tincy_SKU_Master, Tincy_Store_312, on='SKU')
china_import_df = merged_df[merged_df['Vendor'] == 'MA Excellent Products']

#Tincy_Store_312
mean_sales_df = china_import_df.groupby('Day')['Dollar Sales'].sum().reset_index()
mean_sales_df.nsmallest(n=1,columns='Dollar Sales')

Day  Dollar Sales
4  Tuesday      18723.75

کمترین فروش برای روز سه شنبه می باشد .پبشنهاد من این است که  روز دو شنبه تبلیغ برای فروش انجام شود تا  به  روز کم فروش (سه شنبه) نزدیک باشد و یک روز کامل فرصت تبلیغ است.
The lowest sales are for Tuesday. My recommendation is to advertise for sales on Monday so that it is close to the low sales day (Tuesday) and there is a full day of advertising time.

## 2-sheet store 521

In [17]:
Tincy_Store_521=pd.read_excel('TincyCo.xlsx',sheet_name='Store 521')
Tincy_Store_521

DB_ID          SKU  Store       Date Unit Sales  Dollar Sales
0     95435   7312455520    521 2004-08-31          3         68.97
1     95436   7312455520    521 2004-09-03          2         51.98
2     95437   7312455520    521 2004-09-03          2         45.98
3     95438   7312455520    521 2004-09-03          2         45.98
4     95439   7312455520    521 2004-09-07          3         68.97
...     ...          ...    ...        ...        ...           ...
3539  81499  50*12011250    521 2005-03-31          5         49.95
3540  81533  50*12011250    521 2005-05-11          2         19.98
3541  81669  50*12011250    521 2005-10-21          7         69.93
3542  81702  50*12011250    521 2005-12-01          3         29.97
3543  81769  50*12011250    521 2006-02-22          2         19.98

[3544 rows x 6 columns]

In [18]:
Tincy_Store_521.drop_duplicates(inplace=True)

In [19]:
Tincy_Store_521.isna().sum()

DB_ID            0
SKU              0
Store            0
Date             0
Unit Sales      48
Dollar Sales    65
dtype: int64

In [20]:
Tincy_Store_521.dropna(inplace=True)

In [21]:
Tincy_Store_521.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3476 entries, 0 to 3543
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype         
---  ------        --------------  -----         
 0   DB_ID         3476 non-null   int64         
 1   SKU           3476 non-null   object        
 2   Store         3476 non-null   int64         
 3   Date          3476 non-null   datetime64[ns]
 4   Unit Sales    3476 non-null   object        
 5   Dollar Sales  3476 non-null   float64       
dtypes: datetime64[ns](1), float64(1), int64(2), object(2)
memory usage: 190.1+ KB


In [22]:
Tincy_Store_521['week']=Tincy_Store_521['Date'].dt.isocalendar().week

find which week have top sale in store 521

In [23]:
Combine521=Tincy_Store_521[Tincy_Store_521['SKU'].isin(Ma_Excellent_Products)]
Weekly_Sales=Combine521.groupby('week')['Dollar Sales'].sum()
Top_Week=Weekly_Sales.idxmax()
Top_Sales=Weekly_Sales.max()
print(f"The week with the highst sales for MA Excellent products in store 521 is week {Top_Week} with sales of {Top_Sales}$.")

The week with the highst sales for MA Excellent products in store 521 is week 3 with sales of 5057.66$.


Calculate net profit for store 521, item china imports

In [24]:
Tincy_Store_521['Year']=Tincy_Store_521['Date'].dt.year
merged521 = pd.merge(Tincy_SKU_Master, Tincy_Store_521, on='SKU')
china_import_df = merged521[merged521['Vendor'] == 'China Imports'].copy()
china_import_df['Net Profit'] = china_import_df['Dollar Sales'] - (china_import_df['Cost'] * china_import_df['Dollar Sales'] / china_import_df['Price'])
china_import_df.reset_index(drop=True)

china_import_df.groupby(["Year"])[['Net Profit']].sum().reset_index()

Year     Net Profit
0  2004  227407.603380
1  2005  180942.520651
2  2006  132827.005402

## 3-sheet_632

In [25]:
Tincy_Store_632=pd.read_excel('TincyCo.xlsx',sheet_name='Store 632')
Tincy_Store_632

DB_ID          SKU  Store       Date Unit Sales  Dollar Sales
0     95610   7312455520    632 2004-08-19          1         22.99
1     95611   7312455520    632 2004-08-20          2         45.98
2     95612   7312455520    632 2004-08-21          2         51.98
3     95613   7312455520    632 2004-08-27          2         45.98
4     95614   7312455520    632 2004-08-28          2         51.98
...     ...          ...    ...        ...        ...           ...
4948  82140  50*12011250    632 2005-05-12          2         19.98
4949  82174  50*12011250    632 2005-06-22   -A45%0 4           NaN
4950  82341  50*12011250    632 2006-01-12   -A45%0 2           NaN
4951  82480  50*12011250    632 2006-06-24          2         19.98
4952  82514  50*12011250    632 2006-08-04          2         19.98

[4953 rows x 6 columns]

In [26]:
Tincy_Store_632.drop_duplicates(inplace=True)

In [27]:
Tincy_Store_632.isna().sum()

DB_ID            0
SKU              0
Store            0
Date             0
Unit Sales      49
Dollar Sales    73
dtype: int64

In [28]:
Tincy_Store_632.dropna(inplace=True)

In [29]:
Tincy_Store_632.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4876 entries, 0 to 4952
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype         
---  ------        --------------  -----         
 0   DB_ID         4876 non-null   int64         
 1   SKU           4876 non-null   object        
 2   Store         4876 non-null   int64         
 3   Date          4876 non-null   datetime64[ns]
 4   Unit Sales    4876 non-null   object        
 5   Dollar Sales  4876 non-null   float64       
dtypes: datetime64[ns](1), float64(1), int64(2), object(2)
memory usage: 266.7+ KB


In [30]:
Tincy_Store_632['week']=Tincy_Store_632['Date'].dt.isocalendar().week

find which week have top sale in store 632

In [31]:
Combine632=Tincy_Store_632[Tincy_Store_632['SKU'].isin(Ma_Excellent_Products)]
Weekly_Sales=Combine632.groupby('week')['Dollar Sales'].sum()
Top_Week=Weekly_Sales.idxmax()
Top_Sales=Weekly_Sales.max()
print(f"The week with the highst sales for MA Excellent products in store 632 is week {Top_Week} with sales of {Top_Sales}$.")

The week with the highst sales for MA Excellent products in store 632 is week 20 with sales of 14569.65$.


Calculate net profit for store 632, item china imports

In [33]:
Tincy_Store_632['Year']=Tincy_Store_632['Date'].dt.year
merged632 = pd.merge(Tincy_SKU_Master, Tincy_Store_632, on='SKU')
china_import_df = merged632[merged632['Vendor'] == 'China Imports'].copy()
china_import_df['Net Profit'] = china_import_df['Dollar Sales'] - (china_import_df['Cost'] * china_import_df['Dollar Sales'] / china_import_df['Price'])
china_import_df.reset_index(drop=True)

china_import_df.groupby(["Year"])[['Net Profit']].sum().reset_index()

Year     Net Profit
0  2004   77686.332963
1  2005  106026.525507
2  2006  157958.431759

## 4-store 415

In [34]:
Tincy_Store_415=pd.read_excel('TincyCo.xlsx',sheet_name='Store 415')
Tincy_Store_415

DB_ID          SKU  Store       Date Unit Sales  Dollar Sales
0     95280   7312455520    415 2004-08-18          1         22.99
1     95281   7312455520    415 2004-08-19          1         25.99
2     95282   7312455520    415 2004-08-20          1         25.99
3     95283   7312455520    415 2004-08-26          1         25.99
4     95284   7312455520    415 2004-09-15          1         22.99
...     ...          ...    ...        ...        ...           ...
3619  85139  50013000110    415 2006-05-30         30        389.70
3620  85140  50013000110    415 2006-05-31         31        402.69
3621  80778  50*12011250    415 2004-11-29          4         39.96
3622  80811  50*12011250    415 2005-01-08          1          9.99
3623  81222  50*12011250    415 2006-05-13          5         49.95

[3624 rows x 6 columns]

In [35]:
Tincy_Store_415.drop_duplicates(inplace=True)

In [36]:
Tincy_Store_415.isna().sum()

DB_ID            0
SKU              0
Store            0
Date             0
Unit Sales      54
Dollar Sales    72
dtype: int64

In [37]:
Tincy_Store_415.dropna(inplace=True)

In [38]:
Tincy_Store_415.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3549 entries, 0 to 3623
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype         
---  ------        --------------  -----         
 0   DB_ID         3549 non-null   int64         
 1   SKU           3549 non-null   object        
 2   Store         3549 non-null   int64         
 3   Date          3549 non-null   datetime64[ns]
 4   Unit Sales    3549 non-null   object        
 5   Dollar Sales  3549 non-null   float64       
dtypes: datetime64[ns](1), float64(1), int64(2), object(2)
memory usage: 194.1+ KB


In [39]:
Tincy_Store_415['week']=Tincy_Store_415['Date'].dt.isocalendar().week

find which week have top sale in store 415

In [40]:
Combine415=Tincy_Store_415[Tincy_Store_415['SKU'].isin(Ma_Excellent_Products)]
Weekly_Sales=Combine415.groupby('week')['Dollar Sales'].sum()
Top_Week=Weekly_Sales.idxmax()
Top_Sales=Weekly_Sales.max()
print(f"The week with the highst sales for MA Excellent products in store 415 is week {Top_Week} with sales of {Top_Sales}$.")

The week with the highst sales for MA Excellent products in store 415 is week 23 with sales of 4858.53$.


Calculate net profit for store 415, item china imports

In [41]:
Tincy_Store_415['Year']=Tincy_Store_415['Date'].dt.year
merged415 = pd.merge(Tincy_SKU_Master, Tincy_Store_415, on='SKU')
china_import_df = merged415[merged415['Vendor'] == 'China Imports'].copy()
china_import_df['Net Profit'] = china_import_df['Dollar Sales'] - (china_import_df['Cost'] * china_import_df['Dollar Sales'] / china_import_df['Price'])
china_import_df.reset_index(drop=True)

china_import_df.groupby(["Year"])[['Net Profit']].sum().reset_index()

Year     Net Profit
0  2004    2723.343143
1  2005  404884.978930
2  2006  357562.154707

## 5-store 323

In [42]:
Tincy_Store_323=pd.read_excel('TincyCo.xlsx',sheet_name='Store 323')
Tincy_Store_323

DB_ID          SKU  Store       Date Unit Sales  Dollar Sales
0     95059   7312455520    323 2004-08-24          3         68.97
1     95060   7312455520    323 2004-09-14          3         77.97
2     95061   7312455520    323 2004-09-27          3         68.97
3     95062   7312455520    323 2004-09-27          3         68.97
4     95063   7312455520    323 2004-09-28          3         77.97
...     ...          ...    ...        ...        ...           ...
3456  80212  50*12011250    323 2005-01-29          3         29.97
3457  80213  50*12011250    323 2005-01-31          2         19.98
3458  80289  50*12011250    323 2005-05-02          7        699.93
3459  80539  50*12011250    323 2006-02-21          5         49.95
3460  80674  50*12011250    323 2006-08-03          2         19.98

[3461 rows x 6 columns]

In [43]:
Tincy_Store_323.drop_duplicates(inplace=True)

In [44]:
Tincy_Store_323.isna().sum()

DB_ID            0
SKU              0
Store            0
Date             0
Unit Sales      58
Dollar Sales    77
dtype: int64

In [45]:
Tincy_Store_323.dropna(inplace=True)

In [46]:
Tincy_Store_323.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3380 entries, 0 to 3460
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype         
---  ------        --------------  -----         
 0   DB_ID         3380 non-null   int64         
 1   SKU           3380 non-null   object        
 2   Store         3380 non-null   int64         
 3   Date          3380 non-null   datetime64[ns]
 4   Unit Sales    3380 non-null   object        
 5   Dollar Sales  3380 non-null   float64       
dtypes: datetime64[ns](1), float64(1), int64(2), object(2)
memory usage: 184.8+ KB


In [47]:
Tincy_Store_323['week']=Tincy_Store_323['Date'].dt.isocalendar().week

find which week have top sale in store 323

In [48]:
Combine323=Tincy_Store_323[Tincy_Store_323['SKU'].isin(Ma_Excellent_Products)]
Weekly_Sales=Combine323.groupby('week')['Dollar Sales'].sum()
Top_Week=Weekly_Sales.idxmax()
Top_Sales=Weekly_Sales.max()
print(f"The week with the highst sales for MA Excellent products in store 323 is week {Top_Week} with sales of {Top_Sales}$.")

The week with the highst sales for MA Excellent products in store 323 is week 52 with sales of 4550.37$.


Calculate net profit for store323, item china imports

In [49]:
Tincy_Store_312['Year']=Tincy_Store_312['Date'].dt.year
merged312 = pd.merge(Tincy_SKU_Master, Tincy_Store_312, on='SKU')
china_import_df = merged312[merged312['Vendor'] == 'China Imports'].copy()
china_import_df['Net Profit'] = china_import_df['Dollar Sales'] - (china_import_df['Cost'] * china_import_df['Dollar Sales'] / china_import_df['Price'])
china_import_df.reset_index(drop=True)

china_import_df.groupby(["Year"])[['Net Profit']].sum().reset_index()

Year     Net Profit
0  2014  301674.235398
1  2015  229927.649174
2  2016  406862.992033